export const products = [
  {
    id: '15',
    name: 'Nutcracker',
    price: 9.95,
    stock: 27,
    collection: 2023,
    color: 'blue',
    size: 20,
    favorite: true,
    category: 'Christmas decorations',
    images: [
      '/assets/products/nutcracker-polyresin-20-cm.jpg',
      '/assets/products/nutcracker-polyresin-20-cm(1).jpg',
    ],
  },
  {
    id: '16',
    name: 'Gingerbread House',
    price: 4.99,
    stock: 8,
    collection: 2023,
    color: 'brown',
    size: 9,
    favorite: true,
    category: 'Tree decorations',
    images: [
      '/assets/products/glass-christmas-ornament-gingerbread-house-gold-9-cm.jpg',
      '/assets/products/glass-christmas-ornament-gingerbread-house-gold-9-cm (1).jpg',
    ],
  },
  {
    id: '17',
    name: 'LED lights warm',
    price: 8.99,
    stock: 20,
    collection: 2023,
    color: 'yellow',
    size: 700,
    favorite: false,
    category: 'Christmas lights',
    images: [
      '/assets/products/led-lights-warm-7-m.jpg',
      '/assets/products/led-lights-warm-7-m(1).jpg',
    ],
  },
];
